nashville-software-school/csharp-dotnet-milestones

3-asp-dotnet-mvc/exercises/MVC_ROUTING_ANIMALS.md

Created a very simple routing exercise for MVC.

Exercises cs

---

1-foundations/resources/FND_TUTORIALS.md
2-databases/resources/DBS_TUTORIALS.md
3-asp-dotnet-mvc/resources/MVC_TUTORIALS.md

I added the same file (with different name each time to reflect the naming conventions for the repo) to milestones 1, 2, & 3, in their respective "resources" folders. If there's a better place, or less repetitive solution, please let me know what you suggest!

added tutorials to resources

---

1-foundations/exercises/FND_V1-ZOOLANDIA.md

I tried to err on the side of making it too easy and included examples to follow. Suggestions welcome!

Zoolandia1 cs

---

1-foundations/exercises/FND_V1-ZOOLANDIA.md
1-foundations/exercises/FND_V2-OVERRIDES.md
1-foundations/exercises/FND_V3-OVERLOADING.md

Added version 3, removed unused old version2, and clarified instructions in version1

Zoolandia3 cs

---

1-foundations/exercises/FND_V3-OVERLOADING.md

fixing typos all day long

---

1-foundations/exercises/FND_V35-BUILDING-YOUR-ZOO.md

added rough draft of zoolandia 3.5

---

1-foundations/exercises/FND_KOANS.md

I added context the instructions of koans.

added context to FND_KOANS.md

---

2-databases/exercises/DBS_SQL_LEARNING-THRU-DOING.md

Clarified the instructions and moved the body of the information into milestones instead of linking to Jurnell's repo

first new draft of the chinook exercise

---

2-databases/exercises/DBS_SQL_LEARNING-THRU-DOING.md

final draft- please double-check lines 12 & 16

Databse cleanup cs

---

3-database-driven-applications/exercises/database/DBS_CLI_ORDERING.md

Please check for typos, unclear directions, or missed menu options.  Thanks.

Initial draft of Bangazon individual exercise

---

3-database-driven-applications/exercises/database/DBS_V8_LINQ+ENTITYFRAMEWORK.md

I added specific instructions regarding how to set up the chinook database. This project uses entity framework, which the students have not seen yet so I guide them through the setup.

Linq Practice

---

3-database-driven-applications/exercises/mvc/PatientProfile.md
3-database-driven-applications/exercises/mvc/VeternaryClinic.md

Drafted two exercises for the introduction to MVC.  Feedback welcome.

Ls databases

---

3-database-driven-applications/exercises/database/DBS_V8_LINQ+ENTITYFRAMEWORK.md

Modify the exercise to only use the chinook db example. Will get into more detail regarding entity framework at a later point.

Modify the exercise to only use the chinook db example

---

3-database-driven-applications/exercises/mvc/MVC_ZOOLANDIA_MVC.md

Added an MVC exercise for Zoolandia with several bonus options

Zoolandia mvc cs

---

1-foundations/resources/FND_ACCESSIBILITY_LEVELS.md

Gives an overview of Accessibility Levels as a primer to Zoolandia, Mathmagican and similar exercises.

Accessibility Levels

---

1-foundations/resources/FND_ACCESSIBILITY_LEVELS.md
1-foundations/resources/FND_COLLECTIONS.md

This PR aims to provide resources around collections. Specifically, provide explanations and examples for `List<T>` and `Array` generic classes.

[Foundations] Collections

---

3-database-driven-applications/exercises/database/DBS_ZOOLANDIA_RAZOR.md

Intended to be a group exercise.
This requires the students to implement a simple web application combining whats what learned in `Saving Variables`, `LearningSQL` and the following presentations:
- https://github.com/nashville-software-school/csharp-dotnet-milestones/blob/master/3-database-driven-applications/resources/database-concepts/LINQ.pdf
- https://github.com/nashville-software-school/csharp-dotnet-milestones/blob/master/3-database-driven-applications/resources/mvc/MVC_with_Razor.pdf

Remixed Zoolandia HTML for the Razor flavor

---

1-foundations/exercises/FND_KOANS.md

Update for koans to use xunit and .net core.

koans update

---

3-database-driven-applications/exercises/database/DBS_SQL_LEARNING-THRU-DOING.md

I left in the parts about installing sqlite3 as I figured the students should have that installed anyway.

Modified directions to use included database file.

---

1-foundations/resources/FND_ACCESSIBILITY_LEVELS.md

Found a typo while looking at the file for templating new resource files.

conbination > combination

---

1-foundations/exercises/2-intermediate/FND_ZOOLANDIA_1.md

@jcockhren These changes are to make the instructions for setting up zoolandia more clear and to remove the reference to a static method, which is a topic we should cover at a later date, not Zoolandia 1.

Kate zoolandia

---

1-foundations/resources/FND_SETUP/virtualbox-setup.md

on the virtual box setup page, fixed some typos

fix a couple of small spelling errors
